config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pushbullet/callback'
  get 'pushbullet/init'
  get 'pushbullet/devices'
  post 'pushbullet/devices/pick', to: 'pushbullet#devices_pick'
  post '/json_entries/:id/refresh', to: 'json_entries#refresh', as: 'json_entry_refresh'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  authenticate :user, ->(u) { u.email == ENV['EMAIL_SEED'] } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :areas do
    resources :json_entries, only: %i[index new create]
  end

  resources :json_entries, only: %i[edit update destroy show]

  resources :items, only: %i[index]

  root to: 'areas#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
# frozen_string_literal: true

class Area < ApplicationRecord
  belongs_to :user
  has_many :json_entries, dependent: :destroy
  has_many :items, through: :json_entries
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :json_entry
end

app/models/json_entry.rb
# frozen_string_literal: true

class JsonEntry < ApplicationRecord
  belongs_to :area
  has_many :items

  validates :name, presence: true
  validates :data, presence: true
end

app/models/pushbullet_setting.rb
# frozen_string_literal: true

class PushbulletSetting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_one :pushbullet_setting, dependent: :destroy
  has_many :areas, dependent: :destroy
  has_many :items, through: :areas, dependent: :destroy

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(email: data['email'],
                         password: Devise.friendly_token[0, 20])
    user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :set_areas, :check_pushbullet

  def home
    render json: { user: current_user, settings: current_user.pushbullet_setting }
  end

  private

  def set_areas
    @areas_navbar = current_user.areas if current_user
  end

  def check_pushbullet
    redirect_to pushbullet_init_path if current_user && current_user.pushbullet_setting.nil?
  end
end

app/controllers/areas_controller.rb
# frozen_string_literal: true

class AreasController < ApplicationController
  before_action :set_area, only: %i[show edit update destroy]

  # GET /areas
  def index
    @areas = current_user.areas
  end

  # GET /areas/1
  def show
    @json_entries = @area.json_entries
    @items = @area.items.order(id: :desc)
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit; end

  # POST /areas
  def create
    @area = current_user.areas.new(area_params)

    if @area.save
      redirect_to @area, notice: "Area was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /areas/1
  def update
    if @area.update(area_params)
      redirect_to @area, notice: "Area was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /areas/1
  def destroy
    @area.destroy
    redirect_to areas_url, notice: "Area was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_area
    @area = Area.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def area_params
    params.require(:area).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = current_user.items.order(id: :desc)
  end
end

app/controllers/json_entries_controller.rb
# frozen_string_literal: true

class JsonEntriesController < ApplicationController
  before_action :set_area, only: %i[new create]
  before_action :set_json_entry, only: %i[show edit update destroy refresh]

  # GET /json_entries/1
  def show
    @items = @json_entry.items.order(id: :desc)
  end

  # GET /json_entries/new
  def new
    @json_entry = JsonEntry.new
  end

  # GET /json_entries/1/edit
  def edit; end

  # POST /json_entries
  def create
    @json_entry = @area.json_entries.new(json_entry_params)

    if @json_entry.save
      redirect_to edit_json_entry_path(@json_entry), notice: 'Json entry was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /json_entries/1
  def update
    if @json_entry.update(json_entry_params)
      redirect_to @json_entry, notice: 'Json entry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /json_entries/1
  def destroy
    @json_entry.destroy
    redirect_to json_entries_url, notice: 'Json entry was successfully destroyed.'
  end

  def refresh
    FetchItemsFromJsonEntry.new(@json_entry).call
    redirect_to json_entry_path(@json_entry)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_json_entry
    @json_entry = JsonEntry.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_area
    @area = Area.find(params[:area_id])
  end

  # Only allow a trusted parameter "white list" through.
  def json_entry_params
    params.require(:json_entry).permit(:area_id, :data, :name, :verb, :post_body)
  end
end

app/controllers/pushbullet_controller.rb
# frozen_string_literal: true

require 'oauth2'
require 'pushbullet'

class PushbulletController < ApplicationController
  before_action :check_pushbullet_setting, only: %i[devices devices_pick]
  skip_before_action :check_pushbullet

  def init
    client = OAuth2::Client.new(ENV['PUSHBULLET_CLIENT_ID'], ENV['PUSHBULLET_CLIENT_SECRET'], authorize_url: 'https://www.pushbullet.com/authorize')
    auth_url = client.auth_code.authorize_url(redirect_uri: pushbullet_callback_url)
    redirect_to auth_url
  end

  def callback
    client = OAuth2::Client.new(ENV['PUSHBULLET_CLIENT_ID'], ENV['PUSHBULLET_CLIENT_SECRET'], token_url: 'https://api.pushbullet.com/oauth2/token')
    auth_token = client.auth_code.get_token(params[:code])

    pushbullet_setting = PushbulletSetting.find_or_initialize_by(user_id: current_user.id)
    pushbullet_setting.access_token = auth_token.token
    pushbullet_setting.save!
    redirect_to pushbullet_devices_path
  end

  def devices
    @devices = pushbullet_client.devices.map { |d| d.slice(:iden, :nickname, :icon) }
  end

  def devices_pick
    current_user.pushbullet_setting.update!(device_iden: params[:iden])
    redirect_to root_path
  end

  private

  def check_pushbullet_setting
    redirect_to pushbullet_init_path unless current_user.pushbullet_setting
  end

  def pushbullet_client
    Pushbullet.new(token: current_user.pushbullet_setting.access_token)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_class?(path)
    current_page?(path) ? 'active' : 'navbutton'
  end
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
        <% area.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', area_path(@area) %>

app/views/areas/index.html.erb
<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= link_to 'Show', area, class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %></td>
        <td><%= link_to 'Edit', edit_area_path(area), class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' }, class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %></td>
        <td><%= link_to 'Ajouter un json', new_area_json_entry_path(area), class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<h1 class="font-bold text-5xl mb-2">
  <%= @area.name %>
</h1>

<h3 class="font-bold text-xl mb-2">Json_entry :</h3>

<ul>
  <% @json_entries.each do |json_entry| %>
    <li class="my-4"><%= json_entry.name %> <%= link_to "Voir", json_entry_path(json_entry), class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %> </li>
  <% end %>
</ul>

<h2 class="font-bold text-2xl my-2">Annonces :</h2>

<div class="flex flex-wrap mx-2">
  <% @items.each do |item| %>
    <%= render partial: "/shared/item", locals: { item: item } %>
  <% end %>
</div>

<%= link_to 'Add Json Entry', new_area_json_entry_path(@area) %> |
<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/items/index.html.erb
<h1 class="font-bold text-5xl mb-2">
  Mes annonces
</h1>

<div class="flex flex-wrap mx-2">
  <% @items.each do |item| %>
    <%= render partial: "shared/item", locals: { item: item } %>
  <% end %>
</div>

app/views/json_entries/_form.html.erb
<%= form_with(model: json_entry, url: [@area, json_entry], local: true) do |form| %>
  <% if json_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(json_entry.errors.count, "error") %> prohibited this json_entry from being saved:</h2>

      <ul>
        <% json_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_area :data %>
  </div>

  <div class="field">
    <%= form.label :POST? %>
    <%= form.check_box :verb %>
  </div>

  <div class="field">
    <%= form.label :post_body %>
    <%= form.text_area :post_body %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/json_entries/edit.html.erb
<h1>Editing Json Entry</h1>

<%= render 'form', json_entry: @json_entry %>

<%= link_to 'Show', @json_entry %> |
<%= link_to "Area #{@json_entry.area}", area_json_entries_path(@json_entry.area) %>

app/views/json_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Json Entries</h1>

<table>
  <thead>
    <tr>
      <th>Area</th>
      <th>Data</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @json_entries.each do |json_entry| %>
      <tr>
        <td><%= json_entry.area_id %></td>
        <td><%= json_entry.data %></td>
        <td><%= json_entry.name %></td>
        <td><%= link_to 'Show', json_entry %></td>
        <td><%= link_to 'Edit', edit_json_entry_path(json_entry) %></td>
        <td><%= link_to 'Destroy', json_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Json Entry', new_json_entry_path %>

app/views/json_entries/new.html.erb
<h1>New Json Entry</h1>

<%= render 'form', json_entry: @json_entry %>

<%= link_to "Area #{@area.name}", area_path(@area) %>

app/views/json_entries/show.html.erb
<h1 class="font-bold text-5xl mb-2">
  <%= @json_entry.name %>
</h1>

<%= link_to 'Mettre à jour', json_entry_refresh_path(@json_entry), method: :post, class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

<h2 class="font-bold text-2xl my-2">Annonces :</h2>

<div class="flex flex-wrap mx-2">
  <% @items.each do |item| %>
    <%= render partial: "shared/item", locals: { item: item } %>
  <% end %>
</div>

<%= link_to 'Edit', edit_json_entry_path(@json_entry) %> |
<%= link_to 'Back', area_path(@json_entry.area) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scrapper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mx-auto">
      <%= render "shared/navbar" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/pushbullet/devices.html.erb
<h1>Appareils</h1>

<%= form_with(url: pushbullet_devices_pick_path, local: true) do |f| %>
  <%= f.collection_radio_buttons :iden, @devices.map {|d| [d[:iden], d[:nickname]]}, :first, :last %>
  <br>
  <%= f.submit %>
<% end %>

app/views/shared/_item.html.erb
<%= link_to item.url, target: "_blank", class:"flex-col rounded overflow-hidden shadow-lg hover:shadow-2xl item-card mx-auto m-4 relative" do %>
  <%= image_tag(item.image, class:"object-cover w-full") %>
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2">
      <%= item.title %>
    </div>
  </div>
  <div class="px-1 py-2 absolute bottom-0">
    <% if item.price%>
    <span
    class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mx-2 my-1"
    ><%= item.price%></span
    >
    <% end %>
    <% if item.area%>
    <span
    class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mx-2 my-1"
    ><%= item.area%></span
    >
    <% end %>
    <% if item.city%>
    <span
    class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mx-2 my-1"
    ><%= item.city%></span
    >
    <% end %>
    <% if item.zipcode%>
    <span
    class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mx-2 my-1"
    ><%= item.zipcode%></span
    >
    <% end %>
    <% if item.nature%>
    <span
    class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mx-2 my-1"
    ><%= item.nature%></span
    >
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<ul class="flex border-b mt-2">
  <li class="mr-1">
    <%= link_to "Mes annonces", items_path, class:current_class?(items_path) %>
  </li>
  <li class="mr-1">
    <%= link_to "Mes areas", root_path, class:current_class?(root_path) %>
  </li>
  <% if @areas_navbar %>
    <% @areas_navbar.each do |area| %>
      <li class="mr-1">
        <%= link_to area.name, area_path(area), class:current_class?(area_path(area)) %>
      </li>
    <% end %>
  <% end %>
</ul>